### PR TITLE
Rendering won't fail when adding a Map{} header

### LINKED ISSUE #178: Map {} cartocss fails in styleForSymbolizer
When using a CartoCSS with `Map` to, for instance, modify the buffer-size the `styleForSymbolizer` fails because style is invalid on later usages:

screen shot 2016-04-28 at 16 41 42

It raises a `Uncaught TypeError: Cannot read property 'radius' of undefined`.

CartoCSS example:

``` css
Map {
  buffer-size: 32;
}

#populated_places_simple_reduced{
  marker-fill-opacity: 0.9;
  marker-line-color: #FFF;
  marker-line-width: 1;
  marker-line-opacity: 1;
  marker-placement: point;
  marker-type: ellipse;
  marker-width: 96;
  marker-fill: #081B47;
  marker-allow-overlap: true;
}
```

### PR DESCRIPTION
**Pull request by fdansv**
Fixes #178 and #160 
cc @rochoa

### CODE REVIEW

File: src/renderer.js [hunk 1]
```diff
@@ -309,7 +309,9 @@ Renderer.prototype = {
 
     // search for hovers and other special rules for the renderer
     layers = this.processLayersRules(layers)
-
+    if (layers[0].shader.attachment === 'Map::__default__') {
```
Comment (rochoa) [inline src/renderer.js]: Wouldn't be better if you just skip them within `forEach`? This way we will just drop it if it's the first _layer_.

Comment (fdansv) [inline src/renderer.js]: Yeah that's a way better solution
